name: Update Bezel JSON

on:
  schedule:
    - cron: '0 6 * * 1' # every Monday 06:00 UTC
  workflow_dispatch: {}

jobs:
  sync-bezel-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch latest bezel.min.json
        run: |
          curl -L -o assets/bezel.min.json \
            https://raw.githubusercontent.com/markbattistella/BezelKit/main/Sources/BezelKit/Resources/bezel.min.json

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes"
          else
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add assets/bezel.min.json
            git commit -m "chore(ios): update bezel.min.json"
            git push
          fi


